# Generated by Django 5.1.7 on 2025-06-01 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(db_index=True, unique=True)),
                ('male_0_9', models.IntegerField(default=0)),
                ('male_10_19', models.IntegerField(default=0)),
                ('male_20_29', models.IntegerField(default=0)),
                ('male_30_39', models.IntegerField(default=0)),
                ('male_40_49', models.IntegerField(default=0)),
                ('male_50_plus', models.IntegerField(default=0)),
                ('female_0_9', models.IntegerField(default=0)),
                ('female_10_19', models.IntegerField(default=0)),
                ('female_20_29', models.IntegerField(default=0)),
                ('female_30_39', models.IntegerField(default=0)),
                ('female_40_49', models.IntegerField(default=0)),
                ('female_50_plus', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Aggregations (incl. Age/Gender)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DetectionData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('male_0_9', models.IntegerField(default=0)),
                ('male_10_19', models.IntegerField(default=0)),
                ('male_20_29', models.IntegerField(default=0)),
                ('male_30_39', models.IntegerField(default=0)),
                ('male_40_49', models.IntegerField(default=0)),
                ('male_50_plus', models.IntegerField(default=0)),
                ('female_0_9', models.IntegerField(default=0)),
                ('female_10_19', models.IntegerField(default=0)),
                ('female_20_29', models.IntegerField(default=0)),
                ('female_30_39', models.IntegerField(default=0)),
                ('female_40_49', models.IntegerField(default=0)),
                ('female_50_plus', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('is_aggregated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Detection Logs',
                'indexes': [
                    models.Index(
                        fields=['timestamp'], name='api_detecti_timesta_8809e8_idx'
                    ),
                    models.Index(
                        fields=['is_aggregated'], name='api_detecti_is_aggr_6628fd_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'confidence_threshold_person',
                    models.FloatField(
                        default=0.5,
                        help_text='Confidence threshold for person detection (0.0-1.0)',
                    ),
                ),
                (
                    'confidence_threshold_face',
                    models.FloatField(
                        default=0.5,
                        help_text='Confidence threshold for face detection (0.0-1.0)',
                    ),
                ),
                (
                    'log_interval_seconds',
                    models.IntegerField(
                        default=60,
                        help_text='Interval in seconds for logging detection data',
                    ),
                ),
                ('last_updated', models.DateTimeField(auto_now=True)),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Model Settings',
            },
        ),
        migrations.CreateModel(
            name='MonthlyAggregation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('male_0_9', models.IntegerField(default=0)),
                ('male_10_19', models.IntegerField(default=0)),
                ('male_20_29', models.IntegerField(default=0)),
                ('male_30_39', models.IntegerField(default=0)),
                ('male_40_49', models.IntegerField(default=0)),
                ('male_50_plus', models.IntegerField(default=0)),
                ('female_0_9', models.IntegerField(default=0)),
                ('female_10_19', models.IntegerField(default=0)),
                ('female_20_29', models.IntegerField(default=0)),
                ('female_30_39', models.IntegerField(default=0)),
                ('female_40_49', models.IntegerField(default=0)),
                ('female_50_plus', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('total_male', models.IntegerField(default=0)),
                ('total_female', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Monthly Age Gender Aggregations '
                                       '(incl. Basic Counts)',
                'db_table': 'api_monthlyaggregation',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
