# Generated by Django 5.2.1 on 2025-07-18 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyaggregation',
            name='female_count',
        ),
        migrations.RemoveField(
            model_name='dailyaggregation',
            name='male_count',
        ),
        migrations.RemoveField(
            model_name='dailyaggregation',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='detectiondata',
            name='female_count',
        ),
        migrations.RemoveField(
            model_name='detectiondata',
            name='male_count',
        ),
        migrations.RemoveField(
            model_name='detectiondata',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='monthlyaggregation',
            name='female_count',
        ),
        migrations.RemoveField(
            model_name='monthlyaggregation',
            name='male_count',
        ),
        migrations.RemoveField(
            model_name='monthlyaggregation',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='monthlyaggregation',
            name='total_female',
        ),
        migrations.RemoveField(
            model_name='monthlyaggregation',
            name='total_male',
        ),
    ]
