# Generated by Django 5.2.1 on 2025-07-18 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_remove_calculated_fields'),
    ]

    operations = [
        # Add composite indexes for common query patterns on DetectionData
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS idx_detectiondata_aggregated_timestamp '
            'ON api_detectiondata (is_aggregated, timestamp DESC);',
            reverse_sql='DROP INDEX IF EXISTS idx_detectiondata_aggregated_timestamp;',
        ),
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS idx_detectiondata_timestamp_desc '
            'ON api_detectiondata (timestamp DESC);',
            reverse_sql='DROP INDEX IF EXISTS idx_detectiondata_timestamp_desc;',
        ),
        # Add indexes for date range queries on DailyAggregation
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS idx_dailyaggregation_date_desc '
            'ON api_dailyaggregation (date DESC);',
            reverse_sql='DROP INDEX IF EXISTS idx_dailyaggregation_date_desc;',
        ),
        # Add indexes for MonthlyAggregation year/month queries
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS idx_monthlyaggregation_year_month_desc '
            'ON api_monthlyaggregation (year DESC, month DESC);',
            reverse_sql='DROP INDEX IF EXISTS idx_monthlyaggregation_year_month_desc;',
        ),
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS idx_monthlyaggregation_year_desc '
            'ON api_monthlyaggregation (year DESC);',
            reverse_sql='DROP INDEX IF EXISTS idx_monthlyaggregation_year_desc;',
        ),
        # Add index for ModelSettings last_updated
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS idx_modelsettings_last_updated_desc '
            'ON api_modelsettings (last_updated DESC);',
            reverse_sql='DROP INDEX IF EXISTS idx_modelsettings_last_updated_desc;',
        ),
    ]
